((channel) => {
const bridgeKey = "__cuemindPageBridge";
if (window[bridgeKey]?.channel === channel) return;

function getPlayerResponse() {
  const player = document.querySelector("#movie_player");
  const currentVideoId = new URL(location.href).searchParams.get("v");
  let liveResponse = null;
  try {
    liveResponse = player?.getPlayerResponse?.() || null;
  } catch {
    // Some YouTube player builds expose the method before it is callable.
  }
  const candidates = [
    liveResponse,
    window.ytplayer?.config?.args?.raw_player_response,
    window.ytInitialPlayerResponse
  ];
  return candidates.find((candidate) => {
    const candidateId = candidate?.videoDetails?.videoId;
    return candidateId && (!currentVideoId || candidateId === currentVideoId);
  }) ||
    null;
}

function readVideo() {
  const response = getPlayerResponse();
  const details = response?.videoDetails || {};
  let playerData = {};
  try {
    playerData = document.querySelector("#movie_player")?.getVideoData?.() || {};
  } catch {
    // Metadata selectors below remain available as a fallback.
  }
  const tracks =
    response?.captions?.playerCaptionsTracklistRenderer?.captionTracks || [];
  const video = document.querySelector("video");
  const url = new URL(location.href);
  const videoId = url.searchParams.get("v") || details.videoId || "";
  return {
    site: "youtube",
    videoId,
    url: videoId ? `https://www.youtube.com/watch?v=${videoId}` : location.href,
    title:
      details.title ||
      playerData.title ||
      document.querySelector("h1 yt-formatted-string")?.textContent?.trim() ||
      document.title.replace(/\s*-\s*YouTube$/, ""),
    author:
      details.author ||
      playerData.author ||
      document.querySelector("#owner #channel-name a")?.textContent?.trim() ||
      "",
    duration: Number(details.lengthSeconds || video?.duration || 0),
    currentTime: Number(video?.currentTime || 0),
    tracks: tracks.map((track, index) => ({
      id: `${track.languageCode}-${track.kind || "manual"}-${index}`,
      languageCode: track.languageCode,
      name: track.name?.simpleText || track.name?.runs?.map((run) => run.text).join("") || track.languageCode,
      isAutoGenerated: track.kind === "asr",
      isTranslatable: Boolean(track.isTranslatable),
      baseUrl: track.baseUrl
    }))
  };
}

function decodeText(text) {
  const textarea = document.createElement("textarea");
  textarea.innerHTML = text;
  return textarea.value;
}

function parseJson3(text) {
  const payload = JSON.parse(text);
  return (payload.events || []).flatMap((event) => {
    const value = (event.segs || [])
      .map((segment) => segment.utf8 || "")
      .join("")
      .replace(/\n/g, " ")
      .trim();
    return value
      ? [{
          start: Number(event.tStartMs || 0) / 1000,
          duration: Number(event.dDurationMs || 0) / 1000,
          text: decodeText(value)
        }]
      : [];
  });
}

function parseXml(text) {
  const documentNode = new DOMParser().parseFromString(text, "text/xml");
  if (documentNode.querySelector("parsererror")) return [];
  const srv3 = [...documentNode.querySelectorAll("p[t]")].map((node) => ({
    start: Number(node.getAttribute("t") || 0) / 1000,
    duration: Number(node.getAttribute("d") || 0) / 1000,
    text: decodeText(node.textContent || "").replace(/\n/g, " ").trim()
  })).filter((entry) => entry.text);
  if (srv3.length) return srv3;
  return [...documentNode.querySelectorAll("text")]
    .map((node) => ({
      start: Number(node.getAttribute("start") || 0),
      duration: Number(node.getAttribute("dur") || 0),
      text: decodeText(node.textContent || "").replace(/\n/g, " ").trim()
    }))
    .filter((entry) => entry.text);
}

function parseVtt(text) {
  const entries = [];
  const timeToSeconds = (value) => {
    const parts = value.replace(",", ".").split(":").map(Number);
    return parts.reduce((total, part) => total * 60 + part, 0);
  };
  for (const block of text.replace(/\r/g, "").split(/\n{2,}/)) {
    const lines = block.split("\n").filter(Boolean);
    const timeIndex = lines.findIndex((line) => line.includes("-->"));
    if (timeIndex < 0) continue;
    const [startText, endText] = lines[timeIndex].split("-->").map((part) => part.trim().split(" ")[0]);
    const start = timeToSeconds(startText);
    const end = timeToSeconds(endText);
    const value = lines.slice(timeIndex + 1).join(" ").replace(/<[^>]+>/g, "").trim();
    if (value) entries.push({ start, duration: Math.max(0, end - start), text: decodeText(value) });
  }
  return entries;
}

function timestampToSeconds(value) {
  const parts = String(value || "")
    .trim()
    .split(":")
    .map(Number);
  if (!parts.length || parts.some((part) => !Number.isFinite(part))) return 0;
  return parts.reduce((total, part) => total * 60 + part, 0);
}

function readTranscriptPanel() {
  const rows = [
    ...document.querySelectorAll(
      [
        "ytd-transcript-segment-renderer",
        "yt-transcript-segment-view-model",
        "transcript-segment-view-model"
      ].join(", ")
    )
  ];
  const entries = rows
    .map((row) => {
      const timestamp =
        row.querySelector(
          ".segment-timestamp, [class*='timestamp'], .ytwTranscriptSegmentViewModelTimestamp"
        )?.textContent || "";
      const text =
        row.querySelector(".segment-text, [class*='segment-text']")?.textContent ||
        row.querySelector("[class*='content']")?.textContent ||
        row.querySelector("span.ytAttributedStringHost")?.textContent ||
        "";
      return {
        start: timestampToSeconds(timestamp),
        duration: 0,
        text: text.replace(/\s+/g, " ").trim()
      };
    })
    .filter((entry) => entry.text);
  return entries.map((entry, index) => ({
    ...entry,
    duration: Math.max(0, (entries[index + 1]?.start ?? entry.start + 4) - entry.start)
  }));
}

async function fetchFromTranscriptPanel() {
  const existing = readTranscriptPanel();
  if (existing.length) return existing;

  const section = document.querySelector(
    "ytd-video-description-transcript-section-renderer"
  );
  const button = section?.querySelector("button, tp-yt-paper-button");
  button?.click();

  return new Promise((resolve) => {
    const finish = () => {
      const entries = readTranscriptPanel();
      if (!entries.length) return false;
      observer.disconnect();
      clearTimeout(timer);
      resolve(entries);
      return true;
    };
    const observer = new MutationObserver(finish);
    observer.observe(document.documentElement, { childList: true, subtree: true });
    const timer = setTimeout(() => {
      observer.disconnect();
      resolve(readTranscriptPanel());
    }, 8000);
    finish();
  });
}

function parseCaptionPayload(text) {
  const clean = text.trim();
  if (!clean) return [];
  if (clean.startsWith("{")) return parseJson3(clean);
  if (clean.startsWith("<")) return parseXml(clean);
  if (clean.startsWith("WEBVTT")) return parseVtt(clean);
  return [];
}

async function fetchFromCaptionUrl(baseUrl) {
  if (!baseUrl || !baseUrl.startsWith("https://www.youtube.com/api/timedtext")) {
    throw new Error("字幕地址无效。");
  }
  for (const format of [null, "json3", "vtt", "srv1"]) {
    const url = new URL(baseUrl);
    if (format) url.searchParams.set("fmt", format);
    const response = await fetch(url, { credentials: "include" });
    if (!response.ok) continue;
    const entries = parseCaptionPayload(await response.text());
    if (entries.length) return entries;
  }
  return [];
}

async function fetchInnertubeTracks(videoId) {
  const config = window.ytcfg?.data_ || {};
  const apiKey = config.INNERTUBE_API_KEY;
  const context = config.INNERTUBE_CONTEXT;
  if (!apiKey || !context || !videoId) return [];
  const response = await fetch(
    `/youtubei/v1/player?key=${encodeURIComponent(apiKey)}&prettyPrint=false`,
    {
      method: "POST",
      credentials: "include",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ context, videoId })
    }
  );
  if (!response.ok) return [];
  const payload = await response.json();
  return payload?.captions?.playerCaptionsTracklistRenderer?.captionTracks || [];
}

async function fetchTranscript(baseUrl, videoId, languageCode) {
  const direct = await fetchFromCaptionUrl(baseUrl);
  if (direct.length) return direct;

  const tracks = await fetchInnertubeTracks(videoId);
  const fallbackTrack =
    tracks.find((track) => track.languageCode === languageCode) ||
    tracks.find((track) => !track.kind) ||
    tracks[0];
  if (fallbackTrack?.baseUrl && fallbackTrack.baseUrl !== baseUrl) {
    const fallback = await fetchFromCaptionUrl(fallbackTrack.baseUrl);
    if (fallback.length) return fallback;
  }
  const panelEntries = await fetchFromTranscriptPanel();
  if (panelEntries.length) return panelEntries;
  throw new Error("YouTube 官方字幕暂未返回内容，请稍后重试。");
}

async function handle(action, payload) {
  if (action === "getVideo") return readVideo();
  if (action === "getTranscript") {
    return fetchTranscript(payload.baseUrl, payload.videoId, payload.languageCode);
  }
  if (action === "seek") {
    const video = document.querySelector("video");
    if (!video) throw new Error("未找到播放器。");
    video.currentTime = Math.max(0, Number(payload.seconds) || 0);
    await video.play().catch(() => {});
    return { currentTime: video.currentTime };
  }
  if (action === "getTime") {
    return { currentTime: Number(document.querySelector("video")?.currentTime || 0) };
  }
  throw new Error(`Unsupported action: ${action}`);
}

const messageListener = async (event) => {
  if (event.source !== window || event.data?.channel !== channel || event.data?.direction !== "request") {
    return;
  }
  const { id, action, payload = {} } = event.data;
  try {
    const result = await handle(action, payload);
    window.postMessage({ channel, direction: "response", id, result }, "*");
  } catch (error) {
    window.postMessage(
      { channel, direction: "response", id, error: error.message },
      "*"
    );
  }
};

window.addEventListener("message", messageListener);
window[bridgeKey] = { channel, listener: messageListener };
})(document.currentScript?.dataset.channel || "notivue-page-bridge");
