import {
  CACHE_PREFIX,
  NOTES_KEY,
  SETTINGS_KEY,
  escapeMarkdown,
  formatTime,
  groupTranscript,
  transcriptForPrompt
} from "./shared.js";
import { acquireYouTubeVideo } from "./video-acquisition.js";

const state = {
  tabId: null,
  video: null,
  transcript: [],
  translations: {},
  analysis: null,
  notes: [],
  mode: "original",
  selected: null,
  search: "",
  activeCueId: null,
  loading: false
};

const $ = (selector) => document.querySelector(selector);
const $$ = (selector) => [...document.querySelectorAll(selector)];
const requestedTabId = Number(new URLSearchParams(location.search).get("tabId"));

function showView(id) {
  ["#emptyState", "#loadingState", "#errorState", "#workspace"].forEach((selector) => {
    $(selector).classList.toggle("hidden", selector !== id);
  });
}

function toast(message) {
  const node = $("#toast");
  node.textContent = message;
  node.classList.remove("hidden");
  clearTimeout(toast.timer);
  toast.timer = setTimeout(() => node.classList.add("hidden"), 2400);
}

async function sendTab(message) {
  if (!state.tabId) {
    const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });
    state.tabId = tab?.id;
  }
  if (!state.tabId) throw new Error("未找到当前标签页。");
  const response = await chrome.tabs.sendMessage(state.tabId, message);
  if (!response?.ok) throw new Error(response?.error || "视频页面没有响应。");
  return response.result;
}

async function sendRuntime(message) {
  const response = await chrome.runtime.sendMessage(message);
  if (!response?.ok) throw new Error(response?.error || "请求失败。");
  return response.result;
}

function chooseTrack(tracks) {
  const manual = tracks.filter((track) => !track.isAutoGenerated);
  return (
    manual.find((track) => /^en(?:-|$)/i.test(track.languageCode)) ||
    manual[0] ||
    tracks.find((track) => /^en(?:-|$)/i.test(track.languageCode)) ||
    tracks[0]
  );
}

async function loadCache(videoId) {
  const result = await chrome.storage.local.get(`${CACHE_PREFIX}${videoId}`);
  return result[`${CACHE_PREFIX}${videoId}`] || {};
}

async function saveCache() {
  if (!state.video?.videoId) return;
  await chrome.storage.local.set({
    [`${CACHE_PREFIX}${state.video.videoId}`]: {
      transcript: state.transcript,
      translations: state.translations,
      analysis: state.analysis,
      updatedAt: Date.now()
    }
  });
}

async function loadNotes() {
  const stored = await chrome.storage.local.get(NOTES_KEY);
  const all = Array.isArray(stored[NOTES_KEY]) ? stored[NOTES_KEY] : [];
  state.notes = all
    .filter((note) => note.videoId === state.video?.videoId)
    .sort((a, b) => a.timestamp - b.timestamp || b.createdAt - a.createdAt);
  renderNotes();
}

async function persistNotes(nextVideoNotes) {
  const stored = await chrome.storage.local.get(NOTES_KEY);
  const all = Array.isArray(stored[NOTES_KEY]) ? stored[NOTES_KEY] : [];
  const other = all.filter((note) => note.videoId !== state.video.videoId);
  state.notes = nextVideoNotes;
  await chrome.storage.local.set({ [NOTES_KEY]: [...other, ...nextVideoNotes] });
  renderNotes();
}

async function loadCurrentVideo() {
  if (state.loading) return;
  state.loading = true;
  showView("#loadingState");
  $("#loadingMessage").textContent = "读取视频与官方字幕轨道…";
  try {
    const acquisition = await acquireYouTubeVideo({
      tabs: chrome.tabs,
      scripting: chrome.scripting,
      requestedTabId: state.tabId || requestedTabId
    });
    state.tabId = acquisition.tabId;
    const video = acquisition.video;
    const videoChanged = state.video?.videoId !== video.videoId;
    state.video = video;
    if (videoChanged) {
      state.transcript = [];
      state.translations = {};
      state.analysis = null;
      state.mode = "original";
    }

    const cached = await loadCache(video.videoId);
    if (cached.transcript?.length) {
      state.transcript = cached.transcript;
      state.translations = cached.translations || {};
      state.analysis = cached.analysis || null;
    } else {
      const track = chooseTrack(video.tracks || []);
      if (!track) throw new Error("这个视频没有可用的官方字幕轨道。");
      $("#loadingMessage").textContent = `读取 ${track.name} 字幕…`;
      const rawEntries = await sendTab({
        action: "site:getTranscript",
        baseUrl: track.baseUrl,
        videoId: video.videoId,
        languageCode: track.languageCode
      });
      state.transcript = groupTranscript(rawEntries);
      if (!state.transcript.length) throw new Error("字幕轨道为空或暂不可用。");
      await saveCache();
    }

    renderVideo();
    renderTranscript();
    renderOverview();
    await loadNotes();
    showView("#workspace");
    startPlaybackTracking();
  } catch (error) {
    if (error.code === "NO_YOUTUBE_TAB") {
      $("#emptyMessage").textContent = error.message;
      showView("#emptyState");
      return;
    }
    $("#errorMessage").textContent = error.message;
    showView("#errorState");
  } finally {
    state.loading = false;
  }
}

function renderVideo() {
  $("#videoTitle").textContent = state.video.title || "Untitled video";
  $("#videoAuthor").textContent = state.video.author || "YouTube";
  $("#durationLabel").textContent = formatTime(state.video.duration);
}

function appendHighlightedText(node, text, query) {
  if (!query) {
    node.textContent = text;
    return;
  }
  const lower = text.toLocaleLowerCase();
  const needle = query.toLocaleLowerCase();
  let cursor = 0;
  let index = lower.indexOf(needle);
  while (index >= 0) {
    node.append(document.createTextNode(text.slice(cursor, index)));
    const mark = document.createElement("mark");
    mark.textContent = text.slice(index, index + query.length);
    node.append(mark);
    cursor = index + query.length;
    index = lower.indexOf(needle, cursor);
  }
  node.append(document.createTextNode(text.slice(cursor)));
}

function renderTranscript() {
  const list = $("#transcriptList");
  list.replaceChildren();
  const query = state.search.trim();
  let matches = 0;
  for (const cue of state.transcript) {
    const translated = state.translations[cue.id] || "";
    const visibleText =
      state.mode === "translated" ? translated || cue.text : `${cue.text} ${translated}`;
    if (query && visibleText.toLocaleLowerCase().includes(query.toLocaleLowerCase())) matches += 1;

    const row = document.createElement("article");
    row.className = `cue${state.activeCueId === cue.id ? " active" : ""}`;
    row.dataset.id = cue.id;
    row.dataset.start = String(cue.start);

    const time = document.createElement("button");
    time.className = "cue-time";
    time.textContent = formatTime(cue.start);
    time.addEventListener("click", () => seek(cue.start));

    const body = document.createElement("div");
    if (state.mode !== "translated") {
      const original = document.createElement("p");
      original.dataset.role = "original";
      appendHighlightedText(original, cue.text, query);
      body.append(original);
    }
    if (state.mode !== "original") {
      const translation = document.createElement("p");
      translation.className = "translation";
      translation.dataset.role = "translation";
      appendHighlightedText(translation, translated || "尚未翻译", query);
      body.append(translation);
    }
    row.append(time, body);
    list.append(row);
  }
  $("#searchCount").textContent = query ? `${matches} 条` : "";
}

async function seek(seconds) {
  await sendTab({ action: "site:seek", seconds }).catch((error) => toast(error.message));
}

function setMode(mode) {
  state.mode = mode;
  $$(".mode-btn").forEach((button) => button.classList.toggle("active", button.dataset.mode === mode));
  renderTranscript();
  if (mode !== "original" && Object.keys(state.translations).length === 0) translateTranscript();
}

async function translateTranscript() {
  const button = $("#translateBtn");
  const missing = state.transcript.filter((cue) => !state.translations[cue.id]);
  if (!missing.length) {
    toast("译文已完成");
    return;
  }
  const settings = await chrome.storage.local.get(SETTINGS_KEY);
  const targetLanguage = settings[SETTINGS_KEY]?.targetLanguage || "简体中文";
  button.disabled = true;
  try {
    for (let index = 0; index < missing.length; index += 20) {
      const batch = missing.slice(index, index + 20).map(({ id, text }) => ({ id, text }));
      button.textContent = `翻译 ${Math.min(index + 20, missing.length)}/${missing.length}`;
      const result = await sendRuntime({ action: "ai:translate", items: batch, targetLanguage });
      for (const item of result.translations || []) {
        if (item.id && item.text) state.translations[item.id] = item.text;
      }
      await saveCache();
      renderTranscript();
    }
    if (state.mode === "original") setMode("bilingual");
    toast("字幕翻译完成");
  } catch (error) {
    toast(error.message);
  } finally {
    button.disabled = false;
    button.textContent = "翻译";
  }
}

async function analyzeVideo() {
  const button = $("#analyzeBtn");
  button.disabled = true;
  button.textContent = "生成中…";
  try {
    state.analysis = await sendRuntime({
      action: "ai:analyze",
      title: state.video.title,
      author: state.video.author,
      transcript: transcriptForPrompt(state.transcript)
    });
    await saveCache();
    renderOverview();
  } catch (error) {
    toast(error.message);
  } finally {
    button.disabled = false;
    button.textContent = "生成概览";
  }
}

function renderOverview() {
  const hasAnalysis = Boolean(state.analysis);
  $("#overviewEmpty").classList.toggle("hidden", hasAnalysis);
  $("#overviewContent").classList.toggle("hidden", !hasAnalysis);
  if (!hasAnalysis) return;
  $("#summaryText").textContent = state.analysis.summary || "";
  const chapters = $("#chapterList");
  chapters.replaceChildren();
  for (const chapter of state.analysis.chapters || []) {
    const row = document.createElement("article");
    row.className = "chapter";
    const time = document.createElement("button");
    time.className = "cue-time";
    time.textContent = formatTime(chapter.start);
    time.addEventListener("click", () => seek(chapter.start));
    const body = document.createElement("div");
    const title = document.createElement("h3");
    title.textContent = chapter.title;
    const summary = document.createElement("p");
    summary.textContent = chapter.summary;
    body.append(title, summary);
    row.append(time, body);
    chapters.append(row);
  }
  const quotes = $("#quoteList");
  quotes.replaceChildren();
  for (const quote of state.analysis.quotes || []) {
    const row = document.createElement("figure");
    row.className = "quote";
    const text = document.createElement("blockquote");
    text.textContent = `“${quote.text}”`;
    const footer = document.createElement("footer");
    const jump = document.createElement("button");
    jump.className = "cue-time";
    jump.textContent = formatTime(quote.start);
    jump.addEventListener("click", () => seek(quote.start));
    footer.append(jump, document.createTextNode(` · ${quote.insight || ""}`));
    row.append(text, footer);
    quotes.append(row);
  }
}

async function currentTime() {
  const result = await sendTab({ action: "site:getTime" });
  return Number(result.currentTime || 0);
}

async function saveNote(text, timestamp) {
  const clean = String(text || "").trim();
  if (!clean) return;
  const note = {
    id: crypto.randomUUID(),
    videoId: state.video.videoId,
    videoTitle: state.video.title,
    videoUrl: state.video.url,
    timestamp: Number(timestamp || 0),
    text: clean,
    createdAt: Date.now()
  };
  await persistNotes([...state.notes, note].sort((a, b) => a.timestamp - b.timestamp));
  $("#noteInput").value = "";
  toast("笔记已保存");
}

function renderNotes() {
  $("#noteCount").textContent = String(state.notes.length);
  const list = $("#notesList");
  list.replaceChildren();
  if (!state.notes.length) {
    const empty = document.createElement("div");
    empty.className = "notes-empty";
    empty.textContent = "还没有笔记";
    list.append(empty);
    return;
  }
  for (const note of state.notes) {
    const item = document.createElement("article");
    item.className = "note-item";
    const meta = document.createElement("div");
    meta.className = "note-meta";
    const time = document.createElement("button");
    time.className = "cue-time";
    time.textContent = formatTime(note.timestamp);
    time.addEventListener("click", () => seek(note.timestamp));
    const remove = document.createElement("button");
    remove.className = "note-delete";
    remove.title = "删除";
    remove.textContent = "×";
    remove.addEventListener("click", () => persistNotes(state.notes.filter((item) => item.id !== note.id)));
    const text = document.createElement("p");
    text.textContent = note.text;
    meta.append(time, remove);
    item.append(meta, text);
    list.append(item);
  }
}

async function explainSelection() {
  if (!state.selected?.text) return;
  const dialog = $("#explainDialog");
  $("#explainContent").textContent = "正在解释…";
  dialog.showModal();
  try {
    const result = await sendRuntime({
      action: "ai:explain",
      title: state.video.title,
      selection: state.selected.text,
      context: state.selected.context
    });
    const content = $("#explainContent");
    content.replaceChildren();
    const title = document.createElement("h2");
    title.textContent = result.term || state.selected.text;
    const plain = document.createElement("p");
    plain.className = "plain";
    plain.textContent = result.plain || "";
    const detail = document.createElement("p");
    detail.textContent = result.detail || "";
    const example = document.createElement("p");
    example.textContent = result.example ? `例：${result.example}` : "";
    content.append(title, plain, detail, example);
  } catch (error) {
    $("#explainContent").textContent = error.message;
  }
}

function trackSelection() {
  const selection = window.getSelection();
  const text = selection?.toString().trim() || "";
  const anchor = selection?.anchorNode?.parentElement?.closest(".cue");
  if (!text || !anchor || text.length > 500) {
    state.selected = null;
    $("#selectionBar").classList.add("hidden");
    return;
  }
  state.selected = {
    text,
    timestamp: Number(anchor.dataset.start || 0),
    context: anchor.textContent.trim()
  };
  $("#selectionBar").classList.remove("hidden");
}

async function exportMarkdown() {
  if (!state.video) return;
  const sections = [
    `# ${escapeMarkdown(state.video.title)}`,
    "",
    `- 来源：[YouTube](${state.video.url})`,
    `- 作者：${escapeMarkdown(state.video.author)}`,
    ""
  ];
  if (state.analysis?.summary) {
    sections.push("## 概览", "", state.analysis.summary, "");
  }
  if (state.analysis?.chapters?.length) {
    sections.push("## 章节", "");
    for (const chapter of state.analysis.chapters) {
      sections.push(`- [${formatTime(chapter.start)}] ${chapter.title}：${chapter.summary}`);
    }
    sections.push("");
  }
  if (state.analysis?.quotes?.length) {
    sections.push("## 金句", "");
    for (const quote of state.analysis.quotes) {
      sections.push(`> [${formatTime(quote.start)}] ${quote.text}`, "", quote.insight || "", "");
    }
  }
  sections.push("## 笔记", "");
  for (const note of state.notes) sections.push(`- [${formatTime(note.timestamp)}] ${note.text}`);
  sections.push("", "## 逐字稿", "");
  for (const cue of state.transcript) {
    sections.push(`**${formatTime(cue.start)}** ${cue.text}`);
    if (state.translations[cue.id]) sections.push("", state.translations[cue.id]);
    sections.push("");
  }
  const blob = new Blob([sections.join("\n")], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  await chrome.downloads.download({
    url,
    filename: `Notivue/${state.video.title.replace(/[\\/:*?"<>|]/g, "_")}.md`,
    saveAs: true
  });
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

function startPlaybackTracking() {
  clearInterval(startPlaybackTracking.timer);
  startPlaybackTracking.timer = setInterval(async () => {
    if (!state.video || document.hidden) return;
    try {
      const time = await currentTime();
      let active = null;
      for (const cue of state.transcript) {
        if (cue.start <= time) active = cue;
        else break;
      }
      if (active?.id !== state.activeCueId) {
        state.activeCueId = active?.id || null;
        $$(".cue.active").forEach((node) => node.classList.remove("active"));
        const node = document.querySelector(`.cue[data-id="${CSS.escape(state.activeCueId || "")}"]`);
        node?.classList.add("active");
      }
      $("#noteTimeBtn").textContent = formatTime(time);
      $("#noteTimeBtn").dataset.seconds = String(time);
    } catch {
      // Navigation can briefly detach the content script.
    }
  }, 1000);
}

function switchTab(name) {
  $$(".main-tab").forEach((button) => button.classList.toggle("active", button.dataset.tab === name));
  ["transcript", "overview", "notes"].forEach((panel) => {
    $(`#${panel}Panel`).classList.toggle("hidden", panel !== name);
  });
}

function bindEvents() {
  $("#retryBtn").addEventListener("click", loadCurrentVideo);
  $("#errorRetryBtn").addEventListener("click", loadCurrentVideo);
  $("#settingsBtn").addEventListener("click", () => sendRuntime({ action: "settings:open" }));
  $("#exportBtn").addEventListener("click", exportMarkdown);
  $$(".main-tab").forEach((button) => button.addEventListener("click", () => switchTab(button.dataset.tab)));
  $$(".mode-btn").forEach((button) => button.addEventListener("click", () => setMode(button.dataset.mode)));
  $("#translateBtn").addEventListener("click", translateTranscript);
  $("#analyzeBtn").addEventListener("click", analyzeVideo);
  $("#searchInput").addEventListener("input", (event) => {
    state.search = event.target.value;
    renderTranscript();
  });
  $("#transcriptList").addEventListener("mouseup", () => setTimeout(trackSelection));
  $("#explainBtn").addEventListener("click", explainSelection);
  $("#selectionNoteBtn").addEventListener("click", async () => {
    if (!state.selected) return;
    await saveNote(state.selected.text, state.selected.timestamp);
    $("#selectionBar").classList.add("hidden");
  });
  $("#noteTimeBtn").addEventListener("click", async () => {
    const time = await currentTime();
    $("#noteTimeBtn").textContent = formatTime(time);
    $("#noteTimeBtn").dataset.seconds = String(time);
  });
  $("#noteForm").addEventListener("submit", async (event) => {
    event.preventDefault();
    await saveNote($("#noteInput").value, $("#noteTimeBtn").dataset.seconds || 0);
  });
  chrome.tabs.onUpdated.addListener((tabId, changeInfo) => {
    if (tabId === state.tabId && changeInfo.url) setTimeout(loadCurrentVideo, 700);
  });
}

bindEvents();
loadCurrentVideo();
